### NumPy
https://numpy.org/
- ndarray object(n-dimensional array object)
- numerical compution tools
- faster than using list for data
- easy to use
- open source



In [1]:
import numpy as np

In [2]:
data1 = [6.7,5,8,0,1]
arr1 = np.array(data1)
arr1

array([6.7, 5. , 8. , 0. , 1. ])

In [7]:
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)
print(arr2)
print(arr2.shape)  # shape function shows dimention of array
arr2.dtype  # dtype function shows type of data in array

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


dtype('int32')

##### Zeros / Ones
It create arrays of 0 and 1, with a given length or shape
- np.zeros((axis0,axis1,....))/np.ones((axis0,axis1,....))

In [8]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [10]:
# arange(n) is like range, which make list of 0 to n-1, but it makes array of 0 to n-1
np.arange(5)

array([0, 1, 2, 3, 4])

#### random.randn(axis0,axis1,....)
- It creates array randomly with given keys

In [11]:
data = np.random.randn(2,3)
data

array([[-0.50659815,  1.1790573 , -1.09552047],
       [ 0.35969492, -2.84430902, -0.46953447]])

It can be operated like vector when it is equal-size

In [12]:
arr = np.array([[1.,2.,3.],[4.,5.,6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [13]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [14]:
arr-arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [16]:
arr2 = np.array([[0.,4.,1.],[7.,2.,12.]])
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

It can be use for indexing and slicing

In [17]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
arr[5]


5

In [19]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

- Cation: if you slice the original array and restore at another variable and change it, their change can effect the original array so to b sure use "copy()" to restore array

In [25]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d[0,2] == arr2d[0][2]

True

In [30]:
#2-dimentional slicing
print(arr2d[:2,1:])
print(arr2d[2])
print(arr2d[:,:2])
print(arr2d[1,:2])

[[2 3]
 [5 6]]
[7 8 9]
[[1 2]
 [4 5]
 [7 8]]
[4 5]


In [32]:
# Boolean lndexing
names = np.array(['Bob','Joe','Bob'])
data = np.random.randn(3,4)
data[names == 'Bob'] # axis1 = [True, False, True]

array([[-1.0357552 ,  0.01500701, -0.40287044, -0.12028839],
       [ 0.28143735,  1.44271622, -0.2064116 , -0.83580424]])

#### Transpose / Reshape
- T: it transpose 0 and 1 axis as defalt
- transpose((which you want to transpose)): it transpose axis you have chosen
- reshape(axis1, axis2,...): it reshapes array in

In [33]:
arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [34]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [35]:
arr.transpose((1,0))

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])